@startuml
' Vista de componentes del sistema
component "API Gateway" as APIGateway
component Orquestador
component "Servicio Empleado" as ServicioEmpleado
component "Servicio Contrato" as ServicioContrato
database ContratoDB
component "Servicio Entrenamiento" as ServicioEntrenamiento
component "Servicio Nómina" as ServicioNomina
database Kafka
APIGateway --> Orquestador
Orquestador --> ServicioEmpleado
Orquestador --> ServicioContrato
ServicioContrato --> ContratoDB
Orquestador --> ServicioEntrenamiento
Orquestador --> ServicioNomina
Orquestador --> Kafka
@enduml
