@startuml
actor Kafka
Kafka -> ContratoEventListener : contrato.created
ContratoEventListener -> ContratoProjectionRepository : save
ContratoProjectionRepository --> ContratoEventListener : ok
@enduml
